name: flutter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_image: ^0.0.6+1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  http: ^0.13.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
